analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    deprecated_member_use_from_same_package: ignore
    sdk_version_async_exported_from_core: ignore
    unnecessary_null_comparison: ignore
  exclude:
    - "bin/cache/**"
    - "dev/conductor/lib/proto/*"
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "lib/generated/*"

linter:
  rules:
    # - always_declare_return_types
    # - prefer_double_quotes
    # - overridden_fields
    - prefer_single_quotes
    - avoid_void_async
    - prefer_const_constructors
    - prefer_final_locals
    - unnecessary_new
    - unnecessary_parenthesis
    - prefer_const_constructors_in_immutables
    - prefer_final_fields
    - prefer_if_elements_to_conditional_expressions
    - avoid_function_literals_in_foreach_calls
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - directives_ordering
    - cast_nullable_to_non_nullable
    - flutter_style_todos
    - annotate_overrides
    - unnecessary_await_in_return
    - prefer_is_empty
    - prefer_is_not_empty
    - no_logic_in_create_state
    - avoid_unnecessary_containers
    - always_require_non_null_named_parameters
    - avoid_print
    - avoid_bool_literals_in_conditional_expressions
    - avoid_empty_else
    - avoid_field_initializers_in_const_classes
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - control_flow_in_finally
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - null_check_on_nullable_type_parameter
    - null_closures
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_contains
    - prefer_final_in_for_each
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_void_to_null
    - provide_deprecation_message
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - avoid_equals_and_hash_code_on_mutable_classes